global using Covoiturage.Application.Common.Models;
global using Covoiturage.Application.Common.Interfaces;
global using Covoiturage.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using System.Reflection;
