global using Covoiturage.Application.Common.Models;
global using Covoiturage.Application.Common.Interfaces;
global using Covoiturage.Domain.Entities;
global using Covoiturage.Infrastructure.Identity;
global using Covoiturage.Infrastructure.Persistence;
global using Covoiturage.Infrastructure.Photos;
global using Covoiturage.Infrastructure.Services;
global using CloudinaryDotNet;
global using CloudinaryDotNet.Actions;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Configuration;
global using System.Reflection;
global using System.Threading.Tasks;

