/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.14.3.0 (NJsonSchema v10.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export interface ValueTupleOfStringAndString {
    item1: string;
    item2: string;
}

export interface LoginQuery {
    email: string;
    password: string;
}

export interface RegisterCommand {
    email: string;
    password: string;
}

export interface WeatherForecastDto {
    date: Date;
    temperatureC: number;
    temperatureF: number;
    summary: string | undefined;
}

export interface ProblemDetails {
    type: string | undefined;
    title: string | undefined;
    status: number | undefined;
    detail: string | undefined;
    instance: string | undefined;
}

export interface CreateWeatherForecastCommand {
    summary: string;
    temperatureC: number;
}